[project]
channels = ["robostack-staging", "conda-forge"]
description = "Add a short description here"
name = "chandra-project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
